import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Footer() {
  return (
    <footer className="w-full bg-black text-white flex flex-col items-center py-12 px-4 border-t border-neutral-800">
      <div className="flex flex-col items-center w-full max-w-[var(--container)]">
        <Image
          src="/nobills/threeheadlogo.png"
          alt="NOBILLS three-head logo"
          width={160}
          height={60}
          className="mb-6 object-contain w-[120px] sm:w-[160px] h-auto"
          priority
        />
        {/* Newsletter */}
        <form className="w-full max-w-sm flex flex-col items-center gap-3 mb-8">
          <label htmlFor="newsletter" className="sr-only">
            Email address
          </label>
          <div className="flex w-full">
            <input
              id="newsletter"
              type="email"
              required
              placeholder="Your email"
              className="flex-1 px-4 py-2 rounded-l bg-neutral-900 text-white border border-neutral-700 focus:outline-none"
              aria-label="Email address"
            />
            <button
              type="submit"
              className="px-5 py-2 rounded-r bg-neutral-800 border border-neutral-700 text-white font-medium hover:opacity-80 transition"
            >
              Sign Up
            </button>
          </div>
        </form>
        {/* Quick Links */}
        <nav className="flex flex-col sm:flex-row gap-4 justify-center items-center text-sm font-serif tracking-wide">
          <Link href="/about" className="hover:underline underline-offset-4 transition">About</Link>
          <Link href="/contact" className="hover:underline underline-offset-4 transition">Contact</Link>
          <a href="#" className="hover:underline underline-offset-4 transition">Follow</a>
        </nav>
      </div>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-black text-white">
        {children}
        <Footer />
      </body>
    </html>
  );
}
